version: '3.3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2005:1337'
    healthcheck:
      test: socat - TCP4:localhost:1337 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
