version: '3.8'

services:
  server:
    build: .
    ports:
      - '6789:6789'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: socat - TCP4:localhost:6789 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5